use crate::chain::chain_actor::ChainHandle;
use crate::network::node::NodeClient;
use crate::storage::content_id::ContentId;
use crate::storage::db::Storage;

/// B.U.D. Universal Gateway.
/// Resolves a BNS name (.bud) to content stored in B.U.D.
///
/// Bitswap + ContentDiscovery P2P fetch entegre edildi.
pub const MAX_GATEWAY_CONTENT_BYTES: usize = 10 * 1024 * 1024;

fn checked_gateway_content(source: &str, data: Vec<u8>) -> Result<Vec<u8>, String> {
    if data.len() > MAX_GATEWAY_CONTENT_BYTES {
        return Err(format!(
            "gateway content from {source} exceeds {} bytes",
            MAX_GATEWAY_CONTENT_BYTES
        ));
    }
    Ok(data)
}

/// Tarife dayali bir manifest'i baytlara cevir, yoksa `None`.
///
/// `Ok(None)` "bu manifest bir tarif degil" demektir ve cagirani saklanmis
/// bayt yollarina birakir. `Err` ise tarif var ama uretim guvenilmez
/// demektir; bu durumda sonraki yollara **dusulmez**. Duserek devam etmek,
/// dogrulanamayan bir uretimin ardindan baska bir kaynaktan gelen baytlari
/// ayni isim altinda sunmak olurdu.
fn render_from_recipe(
    manifest: &crate::storage::ContentManifest,
) -> Result<Option<Vec<u8>>, String> {
    use crate::storage::generated::ContentSource;
    let spec = match &manifest.source {
        ContentSource::Generated(spec) => spec,
        // `Hybrid` ve `Derived` yalniz tariften uretilemez: ilki yeniden
        // uretilemeyen bir onek tasir, ikincisi master'in baytlarina
        // bagimlidir. Ikisi de saklanmis bayt yollarina birakilir.
        _ => return Ok(None),
    };
    let bytes = crate::storage::generated::generate_content(spec)
        .map_err(|e| format!("recipe did not produce its bytes: {e:?}"))?;
    // Uretilen seyin istenen sey oldugunu dogrula. Tarif zincirde, ama
    // uretici kodun o tarifi dogru okudugunu soyleyen tek sey kimligin
    // tutmasidir.
    //
    // Iki ayrinti kimligi belirler ve ikisi de manifest'ten okunur.
    //
    // Kaynak: manifest kimligi kaynagi **taahhut eder** (bkz. §66),
    // `with_source` kimligi yeniden hesaplar. Kaynaksiz karsilastirmak,
    // ayni baytlarin kaynaksiz halinin kimligiyle kiyaslamak olurdu ve
    // dogru bir uretim bile reddedilirdi.
    //
    // Dilim boyu: kimlik shard listesi uzerinden kurulur, dolayisiyla
    // baytlar orijinaliyle ayni boyda dilimlenmelidir. Tek parca varsaymak
    // cok parcali her nesneyi reddederdi.
    let chunk_size = manifest
        .shards
        .first()
        .map_or(bytes.len(), |shard| shard.size as usize);
    let rebuilt = crate::storage::ContentManifest::from_bytes_sliced(
        &bytes,
        u32::try_from(chunk_size)
            .map_err(|_| "generated object is too large to slice".to_string())?,
    )
    .map_err(|e| format!("generated bytes could not be re-hashed: {e:?}"))?
    .with_source(manifest.source.clone());
    if rebuilt.manifest_id != manifest.manifest_id {
        return Err(
            "generated bytes do not hash to the manifest id that named them; \
             refusing to serve content the recipe does not produce"
                .into(),
        );
    }
    Ok(Some(bytes))
}

pub struct BudGateway {
    chain: ChainHandle,
    network: Option<NodeClient>,
    storage: Option<Storage>,
}

impl BudGateway {
    pub fn new(chain: ChainHandle, network: Option<NodeClient>, storage: Option<Storage>) -> Self {
        Self {
            chain,
            network,
            storage,
        }
    }

    /// Primary entry point for D-Web resolution.
    /// Name: "ayaz.bud" → Returns raw bytes (HTML/Media).
    pub async fn fetch_name_content(&self, name: &str) -> Result<Vec<u8>, String> {
        // 1. Resolve Name → BnsResolved (storage_root + content_id)
        let resolved = self
            .chain
            .bns_resolve_full(name.to_string())
            .await
            .ok_or_else(|| format!("BNS name '{name}' not found"))?;

        if resolved.is_expired {
            return Err(format!("BNS name '{name}' expired"));
        }

        // 2. Derive ContentId from storage_root
        let storage_root = resolved
            .storage_root
            .ok_or_else(|| format!("BNS name '{name}' has no storage binding"))?;

        // Storage_root zaten 32-bayt content anahtarı, ContentId tuple-wrap yeterli.
        let cid = ContentId(storage_root);

        // 3. Tariften dogan icerik: baytlar hicbir yerde saklanmaz.
        //
        // Bu dal en basta gelir cunku digerlerinin arayacagi sey yoktur.
        // `Generated` bir manifest'in baytlari zincirde de, yerel depoda da,
        // uzak eslerde de yoktur; zincirde olan **tariftir**. Dort getirme
        // yolu da saklanmis bayt aradigi icin, uretilmis her icerik bu
        // gecitten "bulunamadi" diye donuyordu: kaydi kabul edilen, ucreti
        // hesaplanan, kopya hedefi belirlenen bir nesne okunamiyordu.
        //
        // `generate_content` tarifi baytlara cevirir ve
        // `ContentManifest::from_bytes_sliced` ile yeniden hash'lenerek
        // manifest kimligine karsi dogrulanir. Yani gecit urettigi seyi
        // dogrular: yanlis bir tarif yanlis bayt uretirse kimlik tutmaz ve
        // istek reddedilir.
        if let Some(manifest) = self.chain.get_storage_manifest(cid).await {
            if let Some(bytes) = render_from_recipe(&manifest)? {
                return checked_gateway_content("on-demand generation", bytes);
            }
        }

        // 4. Local storage lookup (cached content). NOT: Storage::get_content
        //    Bugün stub (kapsamı: blob store henüz yok), bu dal
        //    Doğal olarak ıskalar, NotFound dönüşü P2P hatasına düşer.
        if let Some(ref storage) = self.storage {
            if let Ok(chunk) = storage.get_content(&cid) {
                return checked_gateway_content("local sled storage", chunk);
            }
        }

        // 5. Node-local B.U.D. fetch through the running network stack.
        // This is not a full remote Bitswap requester yet, but it allows the
        // Gateway to read content from the node's own BudBitswap store when the
        // RPC server is co-located with storage.
        if let Some(ref network) = self.network {
            if let Ok(chunk) = network.fetch_local_content(cid.0).await {
                return checked_gateway_content("node-local B.U.D. store", chunk);
            }
        }

        // 6. Remote P2P Bitswap requester. If the content is not available locally,
        // We query connected remote peers over the network.
        if let Some(ref network) = self.network {
            if let Ok(chunk) = network.fetch_remote_content(cid.0).await {
                return checked_gateway_content("remote P2P peer", chunk);
            }
        }

        Err(format!(
            "Content {}:{} not available in local storage, local B.U.D. store, or remote P2P peers.",
            hex::encode(&storage_root[..8]),
            resolved
                .content_id
                .map(|c| hex::encode(&c.as_bytes()[..4]))
                .unwrap_or_else(|| "none".to_string())
        ))
    }

    /// Ayni tarifi, okuyanin istedigi bicimde uret.
    ///
    /// `fetch_name_content` tarifin ham ciktisini doner: uretici ne
    /// uretiyorsa o. Bir tarayici SVG ister, bir cuzdan kucuk bir PNG, bir
    /// galeri baska bir olcu. Uretilmis bir nesne icin bunlarin hepsi **ayni
    /// tariften** dogar; hicbiri saklanmaz.
    ///
    /// Bicim taahhudun parcasidir. PNG olarak uretilen bir tarif, ayni
    /// tarifin SVG'sinden **baska bir nesnedir** ve `render_id` ikisine ayri
    /// kimlik verir. Bu yuzden burada donen kimlik manifest kimligi degil,
    /// bicime bagli render kimligidir; cagiran ikisini karistiramaz cunku
    /// fonksiyon ikisini birlikte doner.
    ///
    /// Yalniz tariften dogan icerik icin calisir. Saklanan baytlarin bicimi
    /// zaten baytlarin kendisidir; onlari yeniden bicimlendirmek bir gecidin
    /// isi degil.
    ///
    /// # Errors
    ///
    /// Isim cozulmezse, icerik tarifli degilse, ya da uretim bicimin
    /// sinirlarini asarsa.
    pub async fn render_name_content(
        &self,
        name: &str,
        format: &crate::storage::render::RenderFormat,
    ) -> Result<(Vec<u8>, [u8; 32]), String> {
        let resolved = self
            .chain
            .bns_resolve_full(name.to_string())
            .await
            .ok_or_else(|| format!("BNS name '{name}' not found"))?;
        if resolved.is_expired {
            return Err(format!("BNS name '{name}' expired"));
        }
        let storage_root = resolved
            .storage_root
            .ok_or_else(|| format!("BNS name '{name}' has no storage binding"))?;
        let cid = ContentId(storage_root);
        let manifest = self
            .chain
            .get_storage_manifest(cid)
            .await
            .ok_or_else(|| format!("BNS name '{name}' resolves to no known manifest"))?;

        let crate::storage::generated::ContentSource::Generated(ref spec) = manifest.source else {
            return Err(
                "only recipe-born content can be rendered into a requested format; \
                 stored bytes already are their format"
                    .into(),
            );
        };

        let bytes = crate::storage::render::render(spec, format)
            .map_err(|e| format!("render failed: {e:?}"))?;
        let bytes = checked_gateway_content("on-demand render", bytes)?;
        let id = crate::storage::render::render_id(format, &bytes);
        Ok((bytes, id))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::storage::generated::{ContentSource, GeneratedSpec, GeneratorId};
    use crate::storage::ContentManifest;

    fn spec() -> GeneratedSpec {
        GeneratedSpec {
            generator: GeneratorId::Avatar,
            seed: [11u8; 32],
            output_len: 32 * 32,
            step_budget: 1_000_000,
        }
    }

    fn generated_manifest() -> ContentManifest {
        let spec = spec();
        let bytes = crate::storage::generated::generate_content(&spec).expect("uretim");
        let len = u32::try_from(bytes.len()).expect("boyut");
        ContentManifest::from_bytes_sliced(&bytes, len)
            .expect("manifest")
            .with_source(ContentSource::Generated(spec))
    }

    /// Tariften dogan icerik gecitten okunabilir.
    ///
    /// Baytlar hicbir yerde saklanmaz; dort getirme yolu da saklanmis bayt
    /// arar. Bu dal olmadan uretilmis her nesne "bulunamadi" donuyordu:
    /// kaydi kabul edilen, kopya hedefi belirlenen bir nesne okunamiyordu.
    #[test]
    fn a_recipe_is_rendered_on_demand() {
        let manifest = generated_manifest();
        let bytes = render_from_recipe(&manifest)
            .expect("tarif uretilebilmeli")
            .expect("uretilmis icerik bayt dondurmeli");
        assert_eq!(bytes.len(), 32 * 32);
        // Ve uretilen sey istenen sey: kimlik tutar.
        //
        // Kaynak geri konur. Manifest kimligi kaynagi taahhut eder (§66), yani
        // ayni baytlarin kaynaksiz hali **baska bir kimlik** verir. Onu
        // beklemek, uretim dogru calisirken bile duser - testin ilk hali tam
        // olarak bunu yapiyordu ve olctugu sey uretim degil kendi kurgusuydu.
        let len = u32::try_from(bytes.len()).expect("boyut");
        let rebuilt = ContentManifest::from_bytes_sliced(&bytes, len)
            .expect("manifest")
            .with_source(manifest.source.clone());
        assert_eq!(rebuilt.manifest_id, manifest.manifest_id);
    }

    /// Uretilen baytlar manifest kimligini tutmuyorsa istek reddedilir.
    ///
    /// Tarif zincirde, ama uretici kodun o tarifi dogru okudugunu soyleyen
    /// tek sey kimligin tutmasidir. Bu denetim olmasa gecit, tarifin
    /// uretmedigi baytlari tarifin adiyla sunardi.
    #[test]
    fn bytes_that_do_not_match_the_id_are_refused() {
        let mut manifest = generated_manifest();
        // Kimlik degistirilir, tarif ayni kalir: uretim artik uyusmaz.
        manifest.manifest_id = crate::storage::ContentId([0xAAu8; 32]);
        let err = render_from_recipe(&manifest).expect_err("uyusmayan kimlik reddedilmeli");
        assert!(
            err.contains("do not hash to the manifest id"),
            "gerekce kimlik uyusmazligini soylemeli: {err}"
        );
    }

    /// Tarife dayanmayan icerik bu dala girmez.
    ///
    /// `Ok(None)` "bu bir tarif degil" demektir ve cagirani saklanmis bayt
    /// yollarina birakir; `Err` olsaydi sakli icerik hic okunamazdi.
    #[test]
    fn stored_content_falls_through_to_the_byte_paths() {
        let bytes = b"siradan tutulan icerik".to_vec();
        let len = u32::try_from(bytes.len()).expect("boyut");
        let manifest = ContentManifest::from_bytes_sliced(&bytes, len).expect("manifest");
        assert!(
            render_from_recipe(&manifest)
                .expect("tutulan icerik hata degil")
                .is_none(),
            "tutulan icerik uretim dalina girmemeli"
        );
    }

    /// `Hybrid` ve `Derived` de saklanmis bayt yollarina birakilir.
    ///
    /// Ikisi de yalniz tariften uretilemez: ilki yeniden uretilemeyen bir
    /// onek tasir, ikincisi master'in baytlarina bagimlidir. Bunlari
    /// uretmeye kalkmak, elde olmayan baytlari varmis gibi gostermek olurdu.
    #[test]
    fn hybrid_content_is_not_rendered_from_the_recipe_alone() {
        let bytes = b"onek arti tarif".to_vec();
        let len = u32::try_from(bytes.len()).expect("boyut");
        let manifest = ContentManifest::from_bytes_sliced(&bytes, len)
            .expect("manifest")
            .with_source(ContentSource::Hybrid {
                prefix_bytes: 4,
                spec: spec(),
            });
        assert!(
            render_from_recipe(&manifest)
                .expect("hybrid hata degil")
                .is_none(),
            "hybrid yalniz tariften uretilemez"
        );
    }
}
