//! B.U.D. 2.0 - crop derivation, in the pattern of `src/storage/derived.rs`.
//!
//! The idea from `src/storage/derived.rs`: an MCU-aligned JPEG crop is REPRODUCIBLE as
//! a deterministic derivative of the master image, so it does not have to be
//! stored. That is I7, the derivation ladder.
//!
//! The evidence, measured in `src/storage`: three aligned crops were
//! EXACTLY identical to the corresponding sub-rectangle of the master's
//! coefficient array, and two deliberately misaligned crops were not. So:
//!
//! - An aligned crop is byte-exactly reproducible, and falls in the
//!   reproducible class.
//! - A misaligned crop is a new object, and falls in the organic class.
//!
//! The JPEG MCU is 16x16 under 4:2:0 chroma. When the crop edges land on MCU
//! boundaries, the DCT coefficients do not change. This module computes the MCU
//! alignment, classifies a crop as aligned or broken, and produces a
//! deterministic derivation record, which can be bound to a PACT as a
//! production proof.

#![forbid(unsafe_code)]

use sha3::{Digest, Sha3_256};

pub const CROP_MAGIC: [u8; 8] = *b"\xB5CROP\0\0\0";
pub const CROP_VERSION: u8 = 1;

/// The JPEG MCU size, under 4:2:0 chroma subsampling, which is the most common.
pub const MCU_SIZE: u32 = 16;

/// A crop derivation record: the master plus the crop region gives a
/// deterministic derivative.
#[derive(Debug, Clone)]
pub struct CropDerivation {
    pub master_content_id: [u8; 32], // the content_id of the master image
    pub x: u32,
    pub y: u32,
    pub w: u32,
    pub h: u32,
    pub aligned: bool, // is it MCU aligned, and therefore byte-exactly reproducible
}

impl CropDerivation {
    pub const DOMAIN: &'static [u8] = b"BDLM_BUD_CROP_V1";

    /// The MCU alignment check: are the crop edges multiples of 16?
    pub fn is_mcu_aligned(x: u32, y: u32, w: u32, h: u32) -> bool {
        x.is_multiple_of(MCU_SIZE)
            && y.is_multiple_of(MCU_SIZE)
            && w.is_multiple_of(MCU_SIZE)
            && h.is_multiple_of(MCU_SIZE)
    }

    /// A new crop record; the alignment is computed automatically.
    pub fn new(master: [u8; 32], x: u32, y: u32, w: u32, h: u32) -> Self {
        CropDerivation {
            master_content_id: master,
            x,
            y,
            w,
            h,
            aligned: Self::is_mcu_aligned(x, y, w, h),
        }
    }

    /// Reproducibility: an aligned crop is regenerated byte-exactly from the
    /// master (I7).
    pub fn is_regenerable(&self) -> bool {
        self.aligned
    }

    /// The commitment of the crop derivative, derived deterministically from the
    /// master and the region.
    pub fn derivation_hash(&self) -> [u8; 32] {
        let mut h = Sha3_256::new();
        h.update(Self::DOMAIN);
        h.update(self.master_content_id);
        h.update(self.x.to_le_bytes());
        h.update(self.y.to_le_bytes());
        h.update(self.w.to_le_bytes());
        h.update(self.h.to_le_bytes());
        h.finalize().into()
    }

    /// Serialises the derivative's region for byte-exact production; the crop
    /// spec.
    pub fn crop_spec(&self) -> Vec<u8> {
        let mut out = Vec::new();
        out.extend_from_slice(&self.master_content_id);
        out.extend_from_slice(&self.x.to_le_bytes());
        out.extend_from_slice(&self.y.to_le_bytes());
        out.extend_from_slice(&self.w.to_le_bytes());
        out.extend_from_slice(&self.h.to_le_bytes());
        out
    }

    pub fn to_blob(&self) -> Vec<u8> {
        let mut out = Vec::new();
        out.extend_from_slice(&CROP_MAGIC);
        out.push(CROP_VERSION);
        out.extend_from_slice(&self.master_content_id);
        out.extend_from_slice(&self.x.to_le_bytes());
        out.extend_from_slice(&self.y.to_le_bytes());
        out.extend_from_slice(&self.w.to_le_bytes());
        out.extend_from_slice(&self.h.to_le_bytes());
        out.push(self.aligned as u8);
        out.extend_from_slice(&self.derivation_hash());
        out
    }

    pub fn from_blob(bytes: &[u8]) -> Option<Self> {
        const HDR: usize = 8 + 1 + 32 + 4 + 4 + 4 + 4 + 1;
        if bytes.len() < HDR + 32 || bytes[0..8] != CROP_MAGIC || bytes[8] != CROP_VERSION {
            return None;
        }
        let mut master = [0u8; 32];
        master.copy_from_slice(&bytes[9..41]);
        let x = u32::from_le_bytes(bytes[41..45].try_into().ok()?);
        let y = u32::from_le_bytes(bytes[45..49].try_into().ok()?);
        let w = u32::from_le_bytes(bytes[49..53].try_into().ok()?);
        let h = u32::from_le_bytes(bytes[53..57].try_into().ok()?);
        let aligned = bytes[57] != 0;
        if bytes.len() != HDR + 32 {
            return None;
        }
        let rec = CropDerivation {
            master_content_id: master,
            x,
            y,
            w,
            h,
            aligned,
        };
        if bytes[HDR..] != rec.derivation_hash() {
            return None;
        }
        Some(rec)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mcu_alignment_detected() {
        // A 4:2:0 MCU is 16x16: aligned edges are byte-exactly reproducible, which
        // is what `src/storage` measured.
        assert!(CropDerivation::is_mcu_aligned(0, 0, 16, 16));
        assert!(CropDerivation::is_mcu_aligned(16, 32, 64, 48));
        assert!(
            !CropDerivation::is_mcu_aligned(1, 0, 16, 16),
            "x is not aligned"
        );
        assert!(
            !CropDerivation::is_mcu_aligned(0, 0, 15, 16),
            "w is not aligned"
        );
        assert!(
            !CropDerivation::is_mcu_aligned(5, 5, 20, 20),
            "neither x nor y is aligned"
        );
    }

    #[test]
    fn aligned_crop_is_regenerable() {
        // I7: an aligned crop is regenerated byte-exactly from the master, so it
        // falls in the reproducible class.
        let master = [7u8; 32];
        let aligned = CropDerivation::new(master, 0, 0, 16, 16);
        assert!(aligned.is_regenerable(), "an aligned crop is reproducible");
        let misaligned = CropDerivation::new(master, 1, 0, 16, 16);
        assert!(
            !misaligned.is_regenerable(),
            "a misaligned crop is a new, organic object"
        );
        // Deterministic: the same region gives the same hash.
        assert_eq!(
            aligned.derivation_hash(),
            CropDerivation::new(master, 0, 0, 16, 16).derivation_hash()
        );
        assert_ne!(aligned.derivation_hash(), misaligned.derivation_hash());
    }

    #[test]
    fn crop_record_roundtrip() {
        let rec = CropDerivation::new([1u8; 32], 16, 32, 64, 48);
        assert!(rec.aligned);
        let blob = rec.to_blob();
        let back = CropDerivation::from_blob(&blob).expect("blob");
        assert_eq!(back.derivation_hash(), rec.derivation_hash());
        assert_eq!(back.x, 16);
        // Tampering is refused.
        let mut bad = blob.clone();
        *bad.last_mut().unwrap() ^= 0x01;
        assert!(CropDerivation::from_blob(&bad).is_none());
        assert!(CropDerivation::from_blob(&[0u8; 10]).is_none());
    }

    #[test]
    fn crop_spec_pins_region() {
        // crop_spec: the master plus the region is the input to byte-exact
        // production, much like a PACT seed.
        let rec = CropDerivation::new([9u8; 32], 32, 0, 48, 16);
        let spec = rec.crop_spec();
        assert_eq!(spec.len(), 32 + 16);
        assert_eq!(&spec[..32], &[9u8; 32]);
        // A different region gives a different spec.
        let rec2 = CropDerivation::new([9u8; 32], 32, 16, 48, 16);
        assert_ne!(rec.crop_spec(), rec2.crop_spec());
    }
}
